export enum PromotionHistorySearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	RANK="RANK",
	DATE_OF_LAST_PROMOTION="DATE_OF_LAST_PROMOTION",
	SENIORITY_ON_EACH_RANK = "SENIORITY_ON_EACH_RANK",
	AUTHORITY_ON_EACH_RANK = "AUTHORITY_ON_EACH_RANK",
 }



