export enum PromotionAttemptSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	SERIAL="SERIAL",
	UNIT_FROM="UNIT_FROM",
	UNIT_TO = "UNIT_TO",
	AUTHORITY = "AUTHORITY",
	RECOMMENDATION_DATE = "RECOMMENDATION_DATE",
	REMARKS = "REMARKS",
 }


