version: "3.8"
services:
    db:
        image: postgres:alpine-15
        environment:
            POSTGRES_PASSWORD: "Test001#"
            POSTGRES_USER: "test"
        ports:
            - "5432:5432"
    api:
        build: ./api
        container_name: abbey_mortgage_backend
        ports:
            - "8080:8080"
        volumes:
            - ./api:/app
