services:
    api:
        container_name: api
        restart: always
        build: .
        ports:
            - 5432:5432
        depends_on:
            - db
        env_file:
            - .env
        environment:
            - DATABASE_URL_DEV=localhost
        volumes:
            - .:/usr/src

    db:
        container_name: postgres
        image: postgres
        ports:
            - 5433:5433
        volumes:
            - data:/data/db
        environment:
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test

volumes:
    data: {}
