export enum TerminationSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	SOS_DATE="SOS_DATE",
	TERMINAL_DATE="TERMINAL_DATE",
	EFFECTIVE_DATE = "EFFECTIVE_DATE",
	TYPE_OF_TERMINATE = "TYPE_OF_TERMINATE",
 }


