export enum AcademicSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	SCHOOL_ATTENDED="SCHOOL_ATTENDED",
	CERTIFICATE_OBTAINED="CERTIFICATE_OBTAINED",
	ADDRESS = "ADDRESS",
	AUTHORITY = "AUTHORITY",
 }



