export enum AwolSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	EFFECTIVE_DATE_OF_AWOL="EFFECTIVE_DATE_OF_AWOL",
	AWOL_AUTHORITY="AWOL_AUTHORITY",
	AUTHORITY = "AUTHORITY",
	EFFECTIVE_DATE_OF_AWOL_CANCELLATION = "EFFECTIVE_DATE_OF_AWOL_CANCELLATION",
	AWOL_CANCELLATION_AUTHORITY = "AWOL_CANCELLATION_AUTHORITY",
 }

 

