export enum MilitaryQualificationSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	CERTIFICATE="CERTIFICATE",
	GRADE="GRADE",
	SCHOOL_NAME = "SCHOOL_NAME",
	SCHOOL_ADDRESS = "SCHOOL_ADDRESS",
	AUTHORITY = "AUTHORITY",
 }


