export enum MilitarySearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	PERSONNEL_STATUS = "PERSONNEL_STATUS",
	EXTENSION_OF_SERVICE = "EXTENSION_OF_SERVICE",
	AUTHORITY_FOR_EXTENSION_OF_SERVICE = "AUTHORITY_FOR_EXTENSION_OF_SERVICE",
	UNIT ="UNIT",
	UNIT_COMMANDER = "UNIT_COMMANDER",
	FORMATION = "FORMATION",
	BRIGADE = "BRIGADE",
	UNIT_LOCATION = "UNIT_LOCATION",
	STATE_UNIT_IS_LOCATED = "STATE_UNIT_IS_LOCATED",
	CORPS = "CORPS",
	AUTHORITY_FOR_CHANGE_OF_CORPS = "AUTHORITY_FOR_CHANGE_OF_CORPS",
	CHANGE_OF_CORPS_DATE = "CHANGE_OF_CORPS_DATE",
	APPOINTMENT = "APPOINTMENT",
	TYPE_OF_COMMISSION = "TYPE_OF_COMMISSION",
	CONVERSION_OF_COMMISSION_AUTHORITY = "CONVERSION_OF_COMMISSION_AUTHORITY",
	ANTI_DATE_ON_COMMISSION = "ANTI_DATE_ON_COMMISSION",
	CONVERSION_DATE = "CONVERSION_DATE",
	EFFECTIVE_DATE_OF_LAST_PROMOTION = "EFFECTIVE_DATE_OF_LAST_PROMOTION",
	LAST_PROMOTION_SIGNATURE_DATE = "LAST_PROMOTION_SIGNATURE_DATE",
	DATE_OF_COMMISSION = "DATE_OF_COMMISSION",
	NEXT_DATE_OF_PROMOTION = "NEXT_DATE_OF_PROMOTION",
	DATE_TAKEN_ON_STRENGTH_IN_PRESENT_UNIT = "DATE_TAKEN_ON_STRENGTH_IN_PRESENT_UNIT",
	POSTING_PROMULGATION = "POSTING_PROMULGATION",
	RUN_OUT_DATE = "RUN_OUT_DATE",
	DATE_OF_ENLISTMENT = "DATE_OF_ENLISTMENT",
	MERGER_OF_SERVICE_DATE = "MERGER_OF_SERVICE_DATE",
	NDA_COURSE = "NDA_COURSE",
	STAFF_COLLEGE_COURSE = "STAFF_COLLEGE_COURSE",
	NDA_GRADE = "NDA_GRADE"
 }

 export interface MilitaryUpdateDetailsSchema {
	PERSONNEL_STATUS:string;
	EXTENSION_OF_SERVICE :string;
	AUTHORITY_FOR_EXTENSION_OF_SERVICE :string;
	UNIT:string;
	UNIT_COMMANDER :string;
	FORMATION :string;
	BRIGADE:string;
	UNIT_LOCATION:string;
	STATE_UNIT_IS_LOCATED :string;
	CORPS :string;
	AUTHORITY_FOR_CHANGE_OF_CORPS :string;
	CHANGE_OF_CORPS_DATE:string;
	CHANGE_OF_CORPS: string;
	APPOINTMENT :string;
	TYPE_OF_COMMISSION :string;
	CONVERSION_OF_COMMISSION_AUTHORITY:string;
	ANTI_DATE_ON_COMMISSION :string;
	CONVERSION_DATE:string;
	EFFECTIVE_DATE_OF_LAST_PROMOTION :string;
	LAST_PROMOTION_SIGNATURE_DATE :string;
	DATE_OF_COMMISSION:string;
	NEXT_DATE_OF_PROMOTION :string;
	DATE_TAKEN_ON_STRENGTH_IN_PRESENT_UNIT:string;
	POSTING_PROMULGATION :string;
	RUN_OUT_DATE :string;
	DATE_OF_ENLISTMENT:string;
	MERGER_OF_SERVICE_DATE :string;
	NDA_COURSE:string;
	STAFF_COLLEGE_COURSE :string;
	NDA_GRADE:string;
 }

 export interface MilitaryDetailsSchema extends MilitaryUpdateDetailsSchema{
	PERSONNEL_NO:string;
 }


 export type MilitaryInfoReqData = {
	[key: string]: any;
	PERSONNEL_NO: string;
  };


  export const reqObjKeys: Record<string, string> = {
	PERSONNEL_STATUS: "PERSONNEL_STATUS",
	EXTENSION_OF_SERVICE_DATE: "EXTENSION_OF_SERVICE",
	AUTHORITY_FOR_EXTENSION_OF_SERVICE: "AUTHORITY_FOR_EXTENSION_OF_SERVICE",
	UNIT: "UNIT",
	UNIT_COMMANDER: "UNIT_COMMANDER",
	FORMATION: "FORMATION",
	BRIGADE: "BRIGADE",
	UNIT_LOCATION: "UNIT_LOCATION",
	STATE_UNIT_IS_LOCATED: "STATE_UNIT_IS_LOCATED",
	CORPS: "CORPS",
	CHANGE_OF_CORPS: "CHANGE_OF_CORPS",
	AUTHORITY_FOR_CHANGE_OF_CORPS:
		"AUTHORITY_FOR_CHANGE_OF_CORPS",
	CHANGE_OF_CORPS_DATE: "CHANGE_OF_CORPS_DATE",
	APPOINTMENT: "APPOINTMENT",
	TYPE_OF_COMMISSION: "TYPE_OF_COMMISSION",
	CONVERSION_OF_COMMISSION_AUTHORITY:
		"CONVERSION_OF_COMMISSION_AUTHORITY",
	ANTI_DATE_ON_COMMISSION_DATE: "ANTI_DATE_ON_COMMISSION",
	CONVERSION_DATE: "CONVERSION_DATE",
	EFFECTIVE_DATE_OF_LAST_PROMOTION_DATE: "EFFECTIVE_DATE_OF_LAST_PROMOTION",
	LAST_PROMOTION_SIGNATURE_DATE: "LAST_PROMOTION_SIGNATURE_DATE",
	DATE_OF_COMMISSION_DATE: "DATE_OF_COMMISSION",
	NEXT_DATE_OF_PROMOTION_DATE: "NEXT_DATE_OF_PROMOTION",
	DATE_TAKEN_ON_STRENGTH_IN_PRESENT_UNIT_DATE:
		"DATE_TAKEN_ON_STRENGTH_IN_PRESENT_UNIT",
	POSTING_PROMULGATION: "POSTING_PROMULGATION",
	RUN_OUT_DATE: "RUN_OUT_DATE",
	DATE_OF_ENLISTMENT_DATE: "DATE_OF_ENLISTMENT",
	MERGER_OF_SERVICE_DATE: "MERGER_OF_SERVICE_DATE",
	NDA_COURSE: "NDA_COURSE",
	STAFF_COLLEGE_COURSE: "STAFF_COLLEGE_COURSE",
	NDA_GRADE: "NDA_GRADE",
	STAFF_COLLEGE: "STAFF_COLLEGE" 
};
