export enum DisciplinaryRecordsSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	OFFENCE="OFFENCE",
	REPORTING_AUTHORITY="REPORTING_AUTHORITY",
	TRYING_OFFICER = "TRYING_OFFICER",
	EFFECTIVE_DATE = "EFFECTIVE_DATE",
	DISPOSE_DATE = "DISPOSE_DATE",
	PENALTY = "PENALTY",
	DATE_ENTERED = "DATE_ENTERED",
	VERDICT = "VERDICT",
	REMARKS="REMARKS"
 }




