export enum NextOfKinSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	RELATIONSHIP="RELATIONSHIP",
	PHONE_NUMBER="PHONE_NUMBER",
	EMAIL = "EMAIL",
	AUTHORITY_CONFIRMING_NOK = "AUTHORITY_CONFIRMING_NOK",
 }


