export enum PromembershipSearchCriteria{
	PERSONNEL_NO="PERSONNEL_NO",
	PROFESSIONAL_BODY="PROFESSIONAL_BODY",
	MEMBERSHIP_NO="MEMBERSHIP_NO",
	STATUS = "STATUS",
	REGISTRATION_DATE = "REGISTRATION_DATE",
	AUTHORITY = "AUTHORITY",
 }



